baseURL = "https://www.mattbrody.io/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Matthew Brody Â· Landing Page"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Matthew Brody"
  email = "hello@mattbrody.io"
  description = "Landing Page"
  bio = "Technology Assistant \nDallas School District"
  avatar = "img/dsd_pic.jpg"
  favicon = "img/mb_favicon.ico"

  [params.contact]
    email = "hello@mattbrody.io"
    linkedin = "https://www.linkedin.com/in/matthew-brody-42b112192/"
    github = "https://github.com/M-Brody"
    twitter = "https://twitter.com/Matthew_Brody_"
    strava = "https://www.strava.com/athletes/20365894"
